[project]
name = "order-service"
version = "0.01"
description = "Application for serving users order"
authors = [
    {name = "Zestros",email = "dardanel2006dan@mail.ru"}
]
license = "MIT"
readme = "README.md"
requires-python = "^3.12"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
